# Simple demo Rakefile to autorun samples in current directory
# adjust path to jruby, ARGS, and or opts as required
# NB: use `-J-` prefix to send java args via jruby
ARGS = '--dev -J-XX:InlineSmallCode=500 -J-Xms256m -J-Xmx2g -J-XX:NewSize=64m -J-XX:MaxNewSize=64m'

# Simple demo Rakefile to autorun samples in current directory

desc 'run demo'
task default: [:demo]

desc 'demo'
task :demo do
  samples_list.shuffle.each { |sample| run_sample sample }
end

def samples_list
  Dir.glob('*.rb').map { |file| File.join(__dir__, file) }
end

def run_sample(sample_name)
  puts "Running #{sample_name}...quit to run next sample"
  system "jruby #{ARGS} #{sample_name}"
end
