# Simple demo Rakefile to autorun samples in current directory
# adjust path to jruby, and or opts as required

SAMPLES_DIR="./"
ARGS = '-J-XX:InlineSmallCode=500 -J-Xms256m -J-Xmx2g -J-XX:NewSize=64m -J-XX:MaxNewSize=64m'

desc 'run demo'
task :default => [:demo]

desc 'demo'
task :demo do
  samples_list.shuffle.each{|sample| run_sample sample}
end

def samples_list
  files = []
  Dir.chdir(SAMPLES_DIR)
  Dir.glob("*.rb").each do |file|
    files << File.join(SAMPLES_DIR, file)
  end
  return files
end

def run_sample(sample_name)
  puts "Running #{sample_name}...quit to run next sample"
  open("|jruby #{ARGS} #{sample_name}", "r") do |io|
    while l = io.gets
      puts(l.chop)
    end
  end
end
