# encoding: utf-8
# frozen_string_literal: true
# Simple demo Rakefile to autorun samples in current directory
# NB: If using atom install build and build-rake packages to run from atom

SAMPLES_DIR = './'

desc 'run demo'
task default: [:demo]

desc 'demo'
task :demo do
  samples_list.shuffle.each { |sample| run_sample sample }
end

def samples_list
  files = []
  Dir.chdir(SAMPLES_DIR)
  Dir.glob('*.rb').each do |file|
    files << File.join(SAMPLES_DIR, file)
  end
  return files
end

def run_sample(sample_name)
  puts "Running #{sample_name}...quit to run next sample"
  open("|jruby #{sample_name}", 'r') do |io|
    while l = io.gets
      puts(l.chop)
    end
  end
end
